name: Publish image to Docker hub
on:
    workflow:
    #this will only run if Dockerfile changes after a push
    push:
        branches:
            - main
        paths:
            - './Dockerfile'
              

  

jobs:
    publich_images:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run:
                ls
            - name: Login to Docker
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKER_HUB_USERNAME}}
                password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

            - name: build image
              run: 
                 
                docker build . -t edwinasweeney/modelbuild:latest
            - name: push image to docker hub
              run: |
                docker push edwinasweeney/modelbuild:latest